version: '3.8'

services:
  python-app:
    build:
      context: ./Backend
    ports:
      - "5000:5000"  # Host port 5000 maps to container port 5000

  node-app:
    build:
      context: ./leetcode-api
    ports:
      - "3001:3000"  # Host port 3001 maps to container port 3000

  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Host port 3000 maps to container port 3000

networks:
  app-network:
    driver: bridge