version: '3.8'

services:
  python-app:
    build:
      context: ./Backend
    ports:
      - "5000:5000"  

  node-app:
    build:
      context: ./leetcode-api
    ports:
      - "3000:3000"  
  
  react-app:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  